/**
 * ISO 3166-1 alpha-3 country codes for visa lookup (MOFA expects nationality).
 * Common Umrah visa nationalities + major countries.
 */
export const COUNTRIES: { code: string; name: string }[] = [
  { code: "IND", name: "India" },
  { code: "PAK", name: "Pakistan" },
  { code: "BGD", name: "Bangladesh" },
  { code: "IDN", name: "Indonesia" },
  { code: "EGY", name: "Egypt" },
  { code: "TUR", name: "Turkey" },
  { code: "NGA", name: "Nigeria" },
  { code: "MAR", name: "Morocco" },
  { code: "AFG", name: "Afghanistan" },
  { code: "IRQ", name: "Iraq" },
  { code: "IRN", name: "Iran" },
  { code: "YEM", name: "Yemen" },
  { code: "SYR", name: "Syria" },
  { code: "LBN", name: "Lebanon" },
  { code: "JOR", name: "Jordan" },
  { code: "PSE", name: "Palestine" },
  { code: "LBY", name: "Libya" },
  { code: "TUN", name: "Tunisia" },
  { code: "DZA", name: "Algeria" },
  { code: "SDN", name: "Sudan" },
  { code: "SOM", name: "Somalia" },
  { code: "MLI", name: "Mali" },
  { code: "SEN", name: "Senegal" },
  { code: "NER", name: "Niger" },
  { code: "BFA", name: "Burkina Faso" },
  { code: "GHA", name: "Ghana" },
  { code: "CIV", name: "Ivory Coast" },
  { code: "CMR", name: "Cameroon" },
  { code: "UZB", name: "Uzbekistan" },
  { code: "KAZ", name: "Kazakhstan" },
  { code: "TJK", name: "Tajikistan" },
  { code: "KGZ", name: "Kyrgyzstan" },
  { code: "TKM", name: "Turkmenistan" },
  { code: "MYS", name: "Malaysia" },
  { code: "THA", name: "Thailand" },
  { code: "PHL", name: "Philippines" },
  { code: "VNM", name: "Vietnam" },
  { code: "MMR", name: "Myanmar" },
  { code: "LKA", name: "Sri Lanka" },
  { code: "NPL", name: "Nepal" },
  { code: "GBR", name: "United Kingdom" },
  { code: "USA", name: "United States" },
  { code: "CAN", name: "Canada" },
  { code: "AUS", name: "Australia" },
  { code: "FRA", name: "France" },
  { code: "DEU", name: "Germany" },
  { code: "SAU", name: "Saudi Arabia" },
  { code: "ARE", name: "United Arab Emirates" },
  { code: "KWT", name: "Kuwait" },
  { code: "BHR", name: "Bahrain" },
  { code: "QAT", name: "Qatar" },
  { code: "OMN", name: "Oman" },
].sort((a, b) => a.name.localeCompare(b.name));
