project_id = "kofijegdzeshitunwddn"

[functions.validate-coupon]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.payu-callback]
verify_jwt = false

[functions.gemini-token]
verify_jwt = false

[functions.voice-ai-lead]
verify_jwt = false

[functions.voice-ai-lead-update]
verify_jwt = false

[functions.itinerary-save]
verify_jwt = false

[functions.voice-ai-session]
verify_jwt = false
